name: 'build-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
    inputs:
      type:
        type: string
        required: true
        description: Action type

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          type: Extract
